### PR TITLE
Polling doesn't stop completely when there is an error in receiveMessage

### PR DESCRIPTION
**Pull request by dannyrscott**

### CODE REVIEW

**Comment by dannyrscott** [comment]
@TomFrost Bump :)

**Comment by TomFrost** [comment]
Oh man, totally missed this. Thanks! I have a couple tweaks before release but I'll grab 'em after merge.

**Comment by TomFrost** [comment]
Published in 0.7.0.

**Comment by dannyrscott** [comment]
👍

**Pull request merged**
