### PR TITLE
Feat: Add support to change message visibility timeout

### PR DESCRIPTION
**Pull request by tothandras**
@TomFrost Implement #11.

### CODE REVIEW

**Comment by tothandras** [comment]
I just see there are tests in the repo. :) I'll add some.

**Comment by TomFrost** [comment]
This is fantastic! I'll look into cutting a new release asap. Thanks for the PR!

**Comment by tothandras** [comment]
@TomFrost Please do so. :) Probably more PRs will be coming and if you can release them quickly we won't need to use our fork.

**Comment by TomFrost** [comment]
Hey @tothandras, I'm working on a release now, and just released that `.release` doesn't actually decrement the in-flight counter. I patched it up quick, but I wanted to let you know that would be in 1.1.0 just in case you already have code against your branch that calls `message.release()` followed by `message.keep()` to make sure the counter stays accurate.

**Comment by tothandras** [comment]
@TomFrost Thanks for letting me know!

**Comment by TomFrost** [comment]
Ah, very cool! And I'm glad you like Squiss :). I've been using SQS since... 2011, I think? I've rewritten this logic so many times, for so many projects, it was time to finally abstract it out. It'd be nice if SQS adopted some of Rabbit or Zero's feature set, though!

**Comment by TomFrost** [comment]
Actually, as an aside, I'm considering working on an optional feature for 1.2.0 after 1.1.0 is released that will support automatically extending the visibility timeout of a message (using your API additions) until you delete() or keep() it. I'd love your thoughts on that, if you have any use cases that might be able to take advantage of such a thing.

**Pull request merged**
