### PR TITLE
Add option to pass in an SQS constructor upon Squiss instantiation

### PR DESCRIPTION
**Pull request by cwhenderson20**
Thanks for all of your work on Squiss! It's worked well for me. This is a small change that allows a user to pass in an SQS constructor upon Squiss instantiation, which will be used rather than the one provided by the SDK.

Although the use case is likely rare, it allows Squiss to function in an environment where SQS should not (or cannot) be used (such as local development of an application that uses SQS for message transport).

### CODE REVIEW

**Comment by TomFrost** [comment]
Nice add! I'm so sorry this sat for so long -- apparently I didn't have this repo set to Watched!

Your code looks excellent-- could I bother you to add a line to the README in this PR? Thanks!

**Comment by cwhenderson20** [comment]
Sure thing! I'll work on it later tonight and update the PR.

**Comment by loris** [comment]
+1, would love to have this merged, it would allow to use `Squiss` with latest version of `aws-sdk`

**Comment by cwhenderson20** [comment]
@TomFrost, I've just now updated the README with the information. Sorry for the delay!

**Comment by TomFrost** [comment]
Fantastic! Sorry for the delay on my part (again) as well. One final thought before merging: Do you think it makes sense to also accept an already-instantiated SQS client? We could check whether we're looking at a constructor or an instance in `opts.sqs` and instantiate only if it's a constructor. Open to your thoughts here :)

**Comment by cwhenderson20** [comment]
It wouldn't be a hard change to make. I guess the question is: is there value in it? Unless other changes are made, it means that the user is responsible for instantiated the SQS instance correctly and that it's using a [relatively] new version of the aws-sdk (given the use of promises).

It would, however, make the library more flexible. I can make the change if you wish.

**Comment by TomFrost** [comment]
Well, supporting it later will be a simple non-breaking change that we could do in a minor release, so let's go with what you have now and I/we can add it later if necessary. Merging!

**Pull request merged**
